import type {
  AplicacionMensual,
  ComunicacionOSPE,
  ComunicacionSubcontratacion,
  Empresa,
  EventoAuditoria,
  OrdenDeTrabajo,
  Recurso,
} from '@/types/nexus';

const TODAY = new Date('2026-08-16T12:00:00');

function addDays(days: number): string {
  const d = new Date(TODAY);
  d.setDate(d.getDate() + days);
  return d.toISOString();
}

export const EMPRESAS: Empresa[] = [
  { id: 'emp-1', razonSocial: 'Austral Servicios Petroleros S.A.', cuit: '30-71234567-8', esSubcontratista: false, color: '#3b82f6' },
  { id: 'emp-2', razonSocial: 'Patagonia Mantenimiento Industrial S.R.L.', cuit: '30-70987654-1', esSubcontratista: false, color: '#a855f7' },
  { id: 'emp-3', razonSocial: 'Rigel Montajes y Andamios S.A.', cuit: '30-71122334-5', esSubcontratista: true, contratistaPrincipalId: 'emp-1', color: '#f59e0b' },
];

export const ORDENES_TRABAJO: OrdenDeTrabajo[] = [
  {
    id: 'ot-1',
    codigo: 'OT-CILP-4471',
    descripcion: 'Mantenimiento mecánico Planta de Coque — CILP',
    empresaId: 'emp-1',
    tipoContrato: 'auditable',
    inspectorYpf: 'Ing. Marcelo Ibáñez',
    areaContractual: 'Mantenimiento Refinería',
    fechaInicio: addDays(-210),
    fechaVencimiento: addDays(38),
  },
  {
    id: 'ot-2',
    codigo: 'OT-YTEC-1188',
    descripcion: 'Soporte técnico laboratorios Y-TEC',
    empresaId: 'emp-2',
    tipoContrato: 'auditable',
    inspectorYpf: 'Lic. Carla Domínguez',
    areaContractual: 'I+D Y-TEC',
    fechaInicio: addDays(-95),
    fechaVencimiento: addDays(120),
  },
  {
    id: 'ot-3',
    codigo: 'OT-CILP-4502',
    descripcion: 'Inspección puntual de válvulas — parada de planta',
    empresaId: 'emp-2',
    tipoContrato: 'control_especial',
    inspectorYpf: 'Ing. Marcelo Ibáñez',
    areaContractual: 'Mantenimiento Refinería',
    fechaInicio: addDays(-3),
    fechaVencimiento: addDays(2),
  },
  {
    id: 'ot-4',
    codigo: 'OT-CILP-4471-SC1',
    descripcion: 'Montaje de andamios — subcontrato de OT-CILP-4471',
    empresaId: 'emp-3',
    tipoContrato: 'subcontrato',
    inspectorYpf: 'Ing. Marcelo Ibáñez',
    areaContractual: 'Mantenimiento Refinería',
    fechaInicio: addDays(-40),
    fechaVencimiento: addDays(80),
    comunicacionSubcontratoAprobada: true,
  },
];

export const COMUNICACIONES_SUBCONTRATACION: ComunicacionSubcontratacion[] = [
  {
    id: 'sc-1',
    subcontratistaEmpresaId: 'emp-3',
    contratistaPrincipalId: 'emp-1',
    otId: 'ot-4',
    estado: 'aprobada',
    fechaSolicitud: addDays(-45),
    fechaResolucion: addDays(-40),
  },
];

export const RECURSOS: Recurso[] = [
  {
    id: 'rec-1',
    tipo: 'personal_dependencia',
    nombre: 'Julián Ferreyra',
    identificador: 'CUIL 20-34556677-3',
    empresaId: 'emp-1',
    otId: 'ot-1',
    estadoAval: 'avalado',
    fechaAfectacion: addDays(-200),
    fechaAvalado: addDays(-198),
    activo: true,
    documentos: [
      { requisitoId: 'alta-temprana-arca', estado: 'validado', fechaCarga: addDays(-205) },
      { requisitoId: 'poliza-art', estado: 'validado', fechaCarga: addDays(-200), fechaVencimiento: addDays(28) },
      { requisitoId: 'seguro-vida-obligatorio', estado: 'validado', fechaCarga: addDays(-200), fechaVencimiento: addDays(160) },
      { requisitoId: 'ddjj-epap', estado: 'validado', fechaCarga: addDays(-200) },
      { requisitoId: 'apto-medico', estado: 'validado', fechaCarga: addDays(-190), fechaVencimiento: addDays(15) },
    ],
    cursos: [{ sitio: 'CILP', entidad: 'UTN', fechaRendido: addDays(-300), fechaVencimiento: addDays(430), resultado: 'aprobado' }],
    credenciales: [{ sitio: 'CILP', solicitadaEl: addDays(-195), estado: 'entregada' }],
  },
  {
    id: 'rec-2',
    tipo: 'personal_dependencia',
    nombre: 'Rosana Quiroga',
    identificador: 'CUIL 27-30112233-9',
    empresaId: 'emp-1',
    otId: 'ot-1',
    estadoAval: 'pendiente_inspector',
    fechaAfectacion: addDays(-6),
    activo: true,
    documentos: [
      { requisitoId: 'alta-temprana-arca', estado: 'validado', fechaCarga: addDays(-7) },
      { requisitoId: 'poliza-art', estado: 'cargado', fechaCarga: addDays(-5), fechaVencimiento: addDays(300), cargaPrevia: true },
      { requisitoId: 'seguro-vida-obligatorio', estado: 'cargado', fechaCarga: addDays(-5), fechaVencimiento: addDays(300), cargaPrevia: true },
      { requisitoId: 'ddjj-epap', estado: 'pendiente' },
      { requisitoId: 'apto-medico', estado: 'pendiente' },
    ],
    cursos: [{ sitio: 'CILP', entidad: 'UTN', resultado: 'pendiente' }],
    credenciales: [{ sitio: 'CILP', estado: 'no_solicitada' }],
  },
  {
    id: 'rec-3',
    tipo: 'personal_independiente',
    nombre: 'Damián Souto (autónomo)',
    identificador: 'CUIL 20-28998877-4',
    empresaId: 'emp-2',
    otId: 'ot-3',
    estadoAval: 'nuevo',
    fechaAfectacion: addDays(-1),
    activo: true,
    documentos: [
      { requisitoId: 'ddjj-independiente', estado: 'cargado', fechaCarga: addDays(-1) },
      { requisitoId: 'constancia-arca-independiente', estado: 'cargado', fechaCarga: addDays(-1) },
      { requisitoId: 'seguro-accidentes-personales', estado: 'pendiente' },
      { requisitoId: 'dni', estado: 'validado', fechaCarga: addDays(-1) },
    ],
  },
  {
    id: 'rec-4',
    tipo: 'vehiculo',
    nombre: 'Toyota Hilux — Flota Austral 07',
    identificador: 'Dominio AF340TR',
    empresaId: 'emp-1',
    otId: 'ot-1',
    estadoAval: 'avalado',
    fechaAfectacion: addDays(-150),
    fechaAvalado: addDays(-148),
    activo: true,
    documentos: [
      { requisitoId: 'titulo-vehiculo', estado: 'validado', fechaCarga: addDays(-150) },
      { requisitoId: 'cedula-verde-azul', estado: 'validado', fechaCarga: addDays(-150) },
      { requisitoId: 'vtv-rto', estado: 'validado', fechaCarga: addDays(-150), fechaVencimiento: addDays(40) },
      { requisitoId: 'seguro-vehicular', estado: 'validado', fechaCarga: addDays(-150), fechaVencimiento: addDays(9) },
    ],
    habilitacionVehicular: { formulario11: 'aprobado', formulario12: 'entregada', comisionGestionVehicular: 'Res. CGV-2026-0341' },
  },
  {
    id: 'rec-5',
    tipo: 'personal_dependencia',
    nombre: 'Enzo Battaglia',
    identificador: 'CUIL 20-33445566-2',
    empresaId: 'emp-2',
    otId: 'ot-2',
    estadoAval: 'avalado',
    fechaAfectacion: addDays(-80),
    fechaAvalado: addDays(-78),
    activo: true,
    documentos: [
      { requisitoId: 'alta-temprana-arca', estado: 'validado', fechaCarga: addDays(-83) },
      { requisitoId: 'poliza-art', estado: 'validado', fechaCarga: addDays(-80), fechaVencimiento: addDays(200) },
      { requisitoId: 'seguro-vida-obligatorio', estado: 'validado', fechaCarga: addDays(-80), fechaVencimiento: addDays(200) },
      { requisitoId: 'ddjj-epap', estado: 'validado', fechaCarga: addDays(-80) },
      { requisitoId: 'apto-medico', estado: 'validado', fechaCarga: addDays(-80), fechaVencimiento: addDays(220) },
    ],
    cursos: [{ sitio: 'Y-TEC', entidad: 'Seguridad Y-TEC', fechaRendido: addDays(-80), fechaVencimiento: addDays(650), resultado: 'aprobado' }],
    credenciales: [{ sitio: 'Y-TEC', solicitadaEl: addDays(-75), estado: 'entregada' }],
  },
  {
    id: 'rec-6',
    tipo: 'personal_dependencia',
    nombre: 'Mauro Cabral',
    identificador: 'CUIL 20-31889900-1',
    empresaId: 'emp-3',
    otId: 'ot-4',
    estadoAval: 'aprobada',
    fechaAfectacion: addDays(-10),
    activo: true,
    documentos: [
      { requisitoId: 'alta-temprana-arca', estado: 'validado', fechaCarga: addDays(-12) },
      { requisitoId: 'poliza-art', estado: 'validado', fechaCarga: addDays(-10), fechaVencimiento: addDays(180) },
      { requisitoId: 'seguro-vida-obligatorio', estado: 'validado', fechaCarga: addDays(-10), fechaVencimiento: addDays(180) },
      { requisitoId: 'ddjj-epap', estado: 'validado', fechaCarga: addDays(-10) },
      { requisitoId: 'apto-medico', estado: 'validado', fechaCarga: addDays(-10), fechaVencimiento: addDays(300) },
    ],
    cursos: [{ sitio: 'CILP', entidad: 'UTN', fechaRendido: addDays(-9), resultado: 'aprobado', fechaVencimiento: addDays(721) }],
    credenciales: [{ sitio: 'CILP', solicitadaEl: addDays(-8), estado: 'solicitada_gip' }],
  },
  {
    id: 'rec-7',
    tipo: 'equipo',
    nombre: 'Grupo Electrógeno Portátil GE-14',
    identificador: 'N° Serie GE14-2291',
    empresaId: 'emp-3',
    otId: 'ot-4',
    estadoAval: 'pendiente_inspector',
    fechaAfectacion: addDays(-4),
    activo: true,
    documentos: [
      { requisitoId: 'vtv-rto', estado: 'vencido', fechaCarga: addDays(-400), fechaVencimiento: addDays(-20) },
    ],
  },
  {
    id: 'rec-8',
    tipo: 'personal_dependencia',
    nombre: 'Gisela Palermo',
    identificador: 'CUIL 27-35667788-0',
    empresaId: 'emp-1',
    otId: 'ot-1',
    estadoAval: 'rechazado',
    fechaAfectacion: addDays(-15),
    activo: true,
    documentos: [
      { requisitoId: 'alta-temprana-arca', estado: 'rechazado', fechaCarga: addDays(-15) },
      { requisitoId: 'poliza-art', estado: 'pendiente' },
      { requisitoId: 'seguro-vida-obligatorio', estado: 'pendiente' },
      { requisitoId: 'ddjj-epap', estado: 'pendiente' },
      { requisitoId: 'apto-medico', estado: 'pendiente' },
    ],
  },
  {
    id: 'rec-9',
    tipo: 'personal_dependencia',
    nombre: 'Hugo Sarmiento',
    identificador: 'CUIL 20-27556699-8',
    empresaId: 'emp-1',
    otId: 'ot-1',
    estadoAval: 'avalado',
    fechaAfectacion: addDays(-320),
    fechaAvalado: addDays(-318),
    activo: false,
    bajaMotivo: 'renuncia',
    bajaFecha: addDays(-5),
    bajaTarjetaInvalidada: true,
    documentos: [
      { requisitoId: 'alta-temprana-arca', estado: 'validado', fechaCarga: addDays(-322) },
      { requisitoId: 'poliza-art', estado: 'validado', fechaCarga: addDays(-320), fechaVencimiento: addDays(45) },
      { requisitoId: 'seguro-vida-obligatorio', estado: 'validado', fechaCarga: addDays(-320), fechaVencimiento: addDays(45) },
      { requisitoId: 'ddjj-epap', estado: 'validado', fechaCarga: addDays(-320) },
      { requisitoId: 'apto-medico', estado: 'validado', fechaCarga: addDays(-320), fechaVencimiento: addDays(45) },
    ],
  },
];

export const COMUNICACIONES_OSPE: ComunicacionOSPE[] = [
  {
    id: 'ospe-1',
    tipo: 'orden_servicio',
    otId: 'ot-1',
    empresaId: 'emp-1',
    motivo: 'Reclamo de habilitación de acceso',
    descripcion: 'Se solicita regularizar la Formulario 7 pendiente de Rosana Quiroga antes del ingreso a planta.',
    estado: 'enviada',
    autor: 'Ing. Marcelo Ibáñez (Inspector YPF)',
    fecha: addDays(-4),
  },
  {
    id: 'ospe-2',
    tipo: 'pedido_empresa',
    otId: 'ot-1',
    empresaId: 'emp-1',
    motivo: 'Respuesta a observación del Inspector',
    descripcion: 'Se adjunta turno de Salud Ocupacional confirmado para el 20/08 y carga previa de ART/SVO en SRC-Digitalización.',
    estado: 'enviada',
    autor: 'Austral Servicios Petroleros S.A.',
    fecha: addDays(-2),
    hiloRespuestaDeId: 'ospe-1',
  },
  {
    id: 'ospe-3',
    tipo: 'pedido_empresa',
    otId: 'ot-3',
    empresaId: 'emp-2',
    motivo: 'Solicitud de afectación de personal',
    descripcion: 'Solicitud de afectación de Damián Souto para inspección puntual de válvulas (Control Especial, 3 días).',
    estado: 'borrador',
    autor: 'Patagonia Mantenimiento Industrial S.R.L.',
    fecha: addDays(-1),
  },
];

export const APLICACIONES_MENSUALES: AplicacionMensual[] = [
  {
    id: 'am-1',
    empresaId: 'emp-1',
    periodo: '2026-08',
    diasHorasDeclarados: true,
    fechaLimiteDeclaracion: addDays(-13),
    planillaGiaCargada: true,
    kmRecorridos: 4210,
    indiceConductaManejo: 92,
    horasFormacionMass: 18,
    bloqueado: true,
  },
  {
    id: 'am-2',
    empresaId: 'emp-2',
    periodo: '2026-08',
    diasHorasDeclarados: false,
    fechaLimiteDeclaracion: addDays(-13),
    planillaGiaCargada: false,
    bloqueado: true,
  },
  {
    id: 'am-3',
    empresaId: 'emp-3',
    periodo: '2026-08',
    diasHorasDeclarados: true,
    fechaLimiteDeclaracion: addDays(-13),
    planillaGiaCargada: false,
    kmRecorridos: 0,
    bloqueado: true,
  },
];

export const EVENTOS_AUDITORIA: EventoAuditoria[] = [
  { id: 'ev-1', tipo: 'alta', recursoId: 'rec-3', empresaId: 'emp-2', fecha: addDays(-1), detalle: 'Alta de Damián Souto (Personal Independiente) en OT-CILP-4502.' },
  { id: 'ev-2', tipo: 'documento_vencido', recursoId: 'rec-7', empresaId: 'emp-3', fecha: addDays(-2), detalle: 'VTV/RTO vencida para Grupo Electrógeno GE-14.' },
  { id: 'ev-3', tipo: 'cambio_estado', recursoId: 'rec-6', empresaId: 'emp-3', fecha: addDays(-3), detalle: 'Mauro Cabral pasó a estado Aprobada, habilitada carga en SRC-Digitalización.' },
  { id: 'ev-4', tipo: 'baja', recursoId: 'rec-9', empresaId: 'emp-1', fecha: addDays(-5), detalle: 'Desafectación de Hugo Sarmiento por renuncia. Tarjeta magnética invalidada ante GIP.' },
  { id: 'ev-5', tipo: 'modificacion_registro', recursoId: 'rec-4', empresaId: 'emp-1', fecha: addDays(-6), detalle: 'Actualización de póliza de Seguro Vehicular — notificado al Estudio Auditor.', notificadoEstudioAuditor: true },
  { id: 'ev-6', tipo: 'comunicacion_enviada', empresaId: 'emp-1', fecha: addDays(-4), detalle: 'OS recibida del Inspector Ibáñez sobre habilitación de acceso (OT-CILP-4471).' },
  { id: 'ev-7', tipo: 'comunicacion_enviada', empresaId: 'emp-1', fecha: addDays(-2), detalle: 'PE enviado en respuesta a observación del Inspector.' },
  { id: 'ev-8', tipo: 'documento_cargado', recursoId: 'rec-2', empresaId: 'emp-1', fecha: addDays(-5), detalle: 'Carga previa de ART y SVO de Rosana Quiroga antes del aval de afectación.' },
  { id: 'ev-9', tipo: 'alta', recursoId: 'rec-8', empresaId: 'emp-1', fecha: addDays(-15), detalle: 'Alta de Gisela Palermo — Alta Temprana ARCA rechazada por inconsistencia de datos.' },
];

export const NEXUS_SEED = {
  empresas: EMPRESAS,
  ordenesTrabajo: ORDENES_TRABAJO,
  comunicacionesSubcontratacion: COMUNICACIONES_SUBCONTRATACION,
  recursos: RECURSOS,
  comunicacionesOspe: COMUNICACIONES_OSPE,
  aplicacionesMensuales: APLICACIONES_MENSUALES,
  eventosAuditoria: EVENTOS_AUDITORIA,
};
